"""Reclaimable-unit recognition (spike level).

This is the O(1) basename pre-check the scanner uses for opaque-blob pruning
(ARCHITECTURE.md §6.2 / §7.1): the moment a directory's name is a known reclaimable unit,
the scanner sums it as one blob and stops descending.

In Phase 1 this grows into the full context-aware classifier — e.g. a `target/` is Rust
build output *only if* a `Cargo.toml` encloses it, `.venv` is verified against a project,
and confidence is tracked. For Phase 0 we only SCAN and REPORT (never delete), so a
basename set is safe and sufficient.
"""

from __future__ import annotations

# basename -> (human label, regeneration command)
# High confidence: these directory names are effectively always regenerable artifacts.
RECLAIMABLE_UNITS: dict[str, tuple[str, str]] = {
    "node_modules": ("node_modules", "npm install"),
    ".venv": (".venv", "pip install -r requirements.txt"),
    "venv": ("venv", "pip install -r requirements.txt"),
    "__pycache__": ("__pycache__", "regenerated on next run"),
    ".pytest_cache": (".pytest_cache", "regenerated by pytest"),
    ".mypy_cache": (".mypy_cache", "regenerated by mypy"),
    ".ruff_cache": (".ruff_cache", "regenerated by ruff"),
    "target": ("target (rust)", "cargo build"),
    ".next": (".next", "next build"),
    ".nuxt": (".nuxt", "nuxt build"),
    ".svelte-kit": (".svelte-kit", "vite build"),
    ".turbo": (".turbo", "turbo build"),
    ".parcel-cache": (".parcel-cache", "regenerated by parcel"),
    ".gradle": (".gradle", "gradle build"),
    "DerivedData": ("DerivedData (xcode)", "xcodebuild"),
}

# Context-sensitive: common artifact names that can also be legitimate user directories.
# Off by default in the scanner; Phase 1's classifier will gate them on project context.
CONTEXT_SENSITIVE_UNITS: dict[str, tuple[str, str]] = {
    "dist": ("dist", "build"),
    "build": ("build", "build"),
    "out": ("out", "build"),
}


def is_reclaimable_unit(
    name: str, include_context_sensitive: bool = False
) -> tuple[str, str] | None:
    """Return (label, regen_command) if `name` is a known reclaimable directory, else None."""
    hit = RECLAIMABLE_UNITS.get(name)
    if hit is not None:
        return hit
    if include_context_sensitive:
        return CONTEXT_SENSITIVE_UNITS.get(name)
    return None
