"""Reclaimable-unit recognition + protect patterns — the data behind the classifier.

Two rule sets, both pure data (docs/04 §4 — "a declarative ruleset, not code"):

  * RECLAIMABLE_UNITS — basename → base regen-cost tier + regeneration command. This is the
    O(1) lookup the scanner uses inline for opaque-blob pruning (ARCHITECTURE.md §6.2/§7.1):
    the moment a directory's name is a known reclaimable unit, the scanner sums it as one
    blob and stops descending. The *base* tier here is a property of the artifact kind
    (cheap vs costly to rebuild); the classifier may still downgrade it to 🔴 using project
    context (e.g. an enclosing repo with uncommitted work).

  * PROTECT_* — patterns that mark a path irreplaceable (🔴). Checked at the TOP of the
    safety lattice (ARCHITECTURE.md §7.2): protections win over everything. Used by the
    project analyzer to list a project's protected paths and by the classifier as its
    fail-safe top layer.
"""

from __future__ import annotations

import fnmatch
from dataclasses import dataclass

from reclaim.core.model import Tier


@dataclass(frozen=True, slots=True)
class UnitRule:
    label: str                 # human label, e.g. "target (rust)"
    regen_command: str         # how to rebuild it
    tier: Tier                 # base regen-cost tier (green cheap / yellow costly)


# High confidence: these directory names are effectively always regenerable artifacts.
# Base tier reflects rebuild *cost*, not safety (safety comes from the classifier lattice).
RECLAIMABLE_UNITS: dict[str, UnitRule] = {
    "node_modules": UnitRule("node_modules", "npm install", Tier.REGENERABLE),
    ".venv": UnitRule(".venv", "pip install -r requirements.txt", Tier.REGENERABLE),
    "venv": UnitRule("venv", "pip install -r requirements.txt", Tier.REGENERABLE),
    "env": UnitRule("env", "pip install -r requirements.txt", Tier.REGENERABLE),
    "__pycache__": UnitRule("__pycache__", "regenerated on next run", Tier.REGENERABLE),
    ".pytest_cache": UnitRule(".pytest_cache", "regenerated by pytest", Tier.REGENERABLE),
    ".mypy_cache": UnitRule(".mypy_cache", "regenerated by mypy", Tier.REGENERABLE),
    ".ruff_cache": UnitRule(".ruff_cache", "regenerated by ruff", Tier.REGENERABLE),
    "target": UnitRule("target (rust)", "cargo build", Tier.REGENERABLE),
    ".next": UnitRule(".next", "next build", Tier.REGENERABLE),
    ".nuxt": UnitRule(".nuxt", "nuxt build", Tier.REGENERABLE),
    ".svelte-kit": UnitRule(".svelte-kit", "vite build", Tier.REGENERABLE),
    ".turbo": UnitRule(".turbo", "turbo build", Tier.REGENERABLE),
    ".parcel-cache": UnitRule(".parcel-cache", "regenerated by parcel", Tier.REGENERABLE),
    ".gradle": UnitRule(".gradle", "gradle build", Tier.REGENERABLE),
    # Costly to rebuild: re-downloads a large toolchain/artifact set → 🟡 (docs/03 §2.2).
    "DerivedData": UnitRule("DerivedData (xcode)", "xcodebuild", Tier.REGENERABLE_COSTLY),
}

# Context-sensitive: common artifact names that can also be legitimate user directories.
# Off by default in the scanner; the classifier gates them on project context.
CONTEXT_SENSITIVE_UNITS: dict[str, UnitRule] = {
    "dist": UnitRule("dist", "build", Tier.REGENERABLE),
    "build": UnitRule("build", "build", Tier.REGENERABLE),
    "out": UnitRule("out", "build", Tier.REGENERABLE),
}


def is_reclaimable_unit(
    name: str, include_context_sensitive: bool = False
) -> UnitRule | None:
    """Return the UnitRule if `name` is a known reclaimable directory, else None."""
    hit = RECLAIMABLE_UNITS.get(name)
    if hit is not None:
        return hit
    if include_context_sensitive:
        return CONTEXT_SENSITIVE_UNITS.get(name)
    return None


# --------------------------------------------------------------------------- #
# Protect patterns — the 🔴 top of the safety lattice (docs/03 §2.4).
# A path matching any of these is irreplaceable and must never be reclaimed.
# --------------------------------------------------------------------------- #

# Secret-bearing / credential files (glob on basename).
PROTECT_SECRET_GLOBS: tuple[str, ...] = (
    ".env", ".env.*", "*.pem", "*.key", "*.p12", "*.pfx",
    "id_rsa", "id_dsa", "id_ecdsa", "id_ed25519",
    "credentials", "*.keystore", ".netrc", "*.ppk",
)

# Local databases / irreplaceable data files (glob on basename).
PROTECT_DATA_GLOBS: tuple[str, ...] = (
    "*.sqlite", "*.sqlite3", "*.db", "*.mdb", "*.dump", "*.sql",
)

# Directory basenames that conventionally hold irreplaceable user data.
PROTECT_DIR_NAMES: frozenset[str] = frozenset({"data", "dumps", "datasets", "backups"})


def _matches_any(name: str, globs: tuple[str, ...]) -> bool:
    return any(fnmatch.fnmatch(name, g) for g in globs)


def protect_reason(name: str, is_dir: bool) -> str | None:
    """If a basename is protected, return a human reason; else None.

    Deterministic and fail-safe: used as the lattice's top layer so protections win over
    any reclaimable-unit match (ARCHITECTURE.md §7.2)."""
    if is_dir:
        if name in PROTECT_DIR_NAMES:
            return f"'{name}/' conventionally holds irreplaceable data"
        return None
    if _matches_any(name, PROTECT_SECRET_GLOBS):
        return "secret-bearing file"
    if _matches_any(name, PROTECT_DATA_GLOBS):
        return "local database / data file"
    return None
